apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
  - ../../secret-manager/base

patchesJson6902:
  - target:
      kind: Application
      name: gitops-config-manager
      version: v1alpha1
      group: argoproj.io
    path: patch-slack-subscription.yaml
  